function f1h = sortnev2_fig_init(f1h,col)
% SORTNEV2_FIG_INIT.M: Build figure window for sortnev2
% HINT: If you can't close a window because of a CloseRequestFcn error, run:
%       delete(get(0,'Children'))

% Create a variable to store the handle of the new GUI figure
% f2 becomes non-empty when the new figure is created.
f1h.fig.f2 = [];

%% Begin Main Figure Main Function
% toggle: 'Menu'/'Toolbar' = 'none'/'figure'
f1h.fig.f1 = figure('Position',[520 170 654 783],'Name','sortnev2',...
    'Toolbar','none','MenuBar','none','NumberTitle','off',...
    'Color',get(0,'defaultUicontrolBackgroundColor'),...
    'CloseRequestFcn', @closefirstfigure);

% Main Controls (Top of window)
f1h.pshbtn.loadnev = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'Callback',@loadnev,'KeyPressFcn',@shortcutKeys,'Visible','off',...
'ListboxTop',0,'String','Load','Tag','pshbtn.loadnev',...
'Position',[0.180 0.928 0.106 0.029]);
f1h.pshbtn.save = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'Callback',@save_Callback,'KeyPressFcn',@shortcutKeys,...
'ListboxTop',0,'String','Save','Tag','pshbtn.save',...
'Position',[0.073 0.928 0.093 0.029]);

f1h.pshbtn.elecnum = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'Callback',loadelec,'KeyPressFcn',@shortcutKeys,...
'Position',[0.073 0.894 0.093 0.028],...
'String','Electrode #','Tag','pshbtn.elecnum');
f1h.pshbtn.prevelec = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'Callback',@elecrement_Callback,'KeyPressFcn',@shortcutKeys,...
'ListboxTop',0,'String','<','Tag','pshbtn.prevelec',...
'Position',[0.180 0.894 0.030 0.028]);
f1h.txtbox.elecnum = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'BackgroundColor',[1 1 1],'FontSize',9,...
'Callback',@elecnum_Callback,...%'KeyPressFcn',@shortcutKeys,...
'ListboxTop',0,'String','1','Style','edit','Tag','txtbox.elecnum',...
'Position',[0.218 0.894 0.030 0.028]);
f1h.pshbtn.nextelec = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'Callback',@elecrement_Callback,'KeyPressFcn',@shortcutKeys,...
'ListboxTop',0,'String','>','Tag','pshbtn.nextelec',...
'Position',[0.256 0.894 0.030 0.028]);

f1h.pshbtn.showall = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'Callback',@showall_Callback,'Enable','on','KeyPressFcn',@shortcutKeys,...
'ListboxTop',0,'String','Show All','Tag','pshbtn.showall',...
'Position',[0.364 0.928 0.101 0.029]);
f1h.txt.username = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'HorizontalAlignment','right','KeyPressFcn',@shortcutKeys,...
'Position',[0.297 0.894 0.058 0.022],...
'String','User:','Style','text','Tag','txt.username');
f1h.txtbox.username = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'HorizontalAlignment','center',...%'KeyPressFcn',@shortcutKeys,...
'Position',[0.364 0.894 0.101 0.029],...
'String','User:','Style','edit','Tag','txtbox.username');

f1h.pshbtn.cluster = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'String','Cluster','Tag','pshbtn.cluster',...
'Position',[0.567 0.928 0.106 0.029],...
'Callback',@cluster_Callback,'KeyPressFcn',@shortcutKeys);
f1h.pshbtn.centroids = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'String','Centroids','Tag','pshbtn.centroids',...
'Position',[0.815 0.927 0.135 0.029],...
'Callback',@centroids_Callback,'KeyPressFcn',@shortcutKeys);
f1h.pop.nclusters = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'Position',[0.677 0.930 0.115 0.026],'BackgroundColor',[1 1 1],...
'String',{ '1'; '2'; '3'; '4' },'Style','popupmenu','Value',2,'Tag','pop.nclusters',...
'KeyPressFcn',@shortcutKeys);


f1h.txt.status = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'FontSize',10,'FontWeight','bold','HorizontalAlignment','left',...
'ListboxTop',0,'String','','Style','text','Tag','txt.status',...
'Position',[0.075 0.857 0.390 0.026]);
f1h.txt.nevfile = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'FontSize',10,'FontWeight','bold','HorizontalAlignment','left',...
'ListboxTop',0,'String','','Style','text','Tag','txt.nevfile',...
'Position',[0.075 0.965 0.875 0.026]);
f1h.txt.nchan = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'FontSize',10,'FontWeight','bold','HorizontalAlignment','left',...
'ListboxTop',0,'String','','Style','text','Tag','txt.nchan',...
'Position',[0.075 0.828 0.390 0.026]);


% Unclassified plot (left side)
f1h.axes.unclassified = axes('Parent',f1h.fig.f1,'Units','normalized',...
'Position',[0.075 0.506 0.396 0.287],'Color',get(f1h.fig.f1,'Color'),...
'XColor',get(0,'defaultaxesXColor'),'YColor',get(0,'defaultaxesYColor'),...
'Tag','unclassified','Visible','on');


% PCA plots on right side
f1h.axes.pc(1) = axes('Parent',f1h.fig.f1,'Units','normalized',...
'Position',[0.567 0.625 0.388 0.257],'Color',get(f1h.fig.f1,'Color'),'Box','off',...
'XColor',get(0,'defaultaxesXColor'),'YColor',get(0,'defaultaxesYColor'),...
'Tag','pc(1).ax','Visible','on','XColor',[0.4 0   0],'YColor',[0 0.4 0  ]);
f1h.axes.pc(2) = axes('Parent',f1h.fig.f1,'Units','normalized',...
'Position',[0.567 0.331 0.388 0.257],'Color',get(f1h.fig.f1,'Color'),'Box','off',...
'XColor',get(0,'defaultaxesXColor'),'YColor',get(0,'defaultaxesYColor'),...
'Tag','pc(2).ax','Visible','on','XColor',[0.4 0   0],'YColor',[0 0   0.4]);
f1h.axes.pc(3) = axes('Parent',f1h.fig.f1,'Units','normalized',...
'Position',[0.567 0.031 0.388 0.257],'Color',get(f1h.fig.f1,'Color'),'Box','off',...
'XColor',get(0,'defaultaxesXColor'),'YColor',get(0,'defaultaxesYColor'),...
'Tag','pc(3).ax','Visible','on','XColor',[0   0.4 0],'YColor',[0 0   0.4]);


%% UNIT CONTROLS
f1h.panel.unitcontrols = uipanel('Parent',f1h.fig.f1,'Units','normalized',...
'Tag','panel.unitcontrols','Title','Sorting','Visible','on',...
'Position',[0.045 0.040 0.450 0.425]);
f1h.txt.unitnum       = uicontrol('Parent',f1h.panel.unitcontrols,'Units','normalized',...
'FontSize',9,'FontWeight','normal','HorizontalAlignment','left',...
'ListboxTop',0,'String','Unit #',     'Style','text','Tag','txt.unitnum',...
'Position',[0.025 0.945 0.250 0.045],'BackgroundColor','r');
f1h.txt.unitdprime    = uicontrol('Parent',f1h.panel.unitcontrols,'Units','normalized',...
'FontSize',9,'FontWeight','normal','HorizontalAlignment','left',...
'ListboxTop',0,'String','d'' =',     'Style','text','Tag','txt.unitdprime',...
'Position',[0.025 0.880 0.250 0.045]);
f1h.txt.saveunit      = uicontrol('Parent',f1h.panel.unitcontrols,'Units','normalized',...
'FontSize',9,'FontWeight','normal','HorizontalAlignment','left',...
'ListboxTop',0,'String','SAVE ?',     'Style','text','Tag','txt.saveunit',...
'Position',[0.025 0.815 0.250 0.045]);
f1h.txt.showtrace     = uicontrol('Parent',f1h.panel.unitcontrols,'Units','normalized',...
'FontSize',9,'FontWeight','normal','HorizontalAlignment','left',...
'ListboxTop',0,'String','Show traces','Style','text','Tag','txt.showtrace',...
'Position',[0.025 0.750 0.250 0.045]);
f1h.txt.meanwave      = uicontrol('Parent',f1h.panel.unitcontrols,'Units','normalized',...
'FontSize',9,'FontWeight','normal','HorizontalAlignment','left',...
'ListboxTop',0,'String','Av waveform','Style','text','Tag','txt.meanwave',...
'Position',[0.025 0.685 0.250 0.045]);
f1h.txt.bringtotop    = uicontrol('Parent',f1h.panel.unitcontrols,'Units','normalized',...
'FontSize',9,'FontWeight','normal','HorizontalAlignment','left',...
'ListboxTop',0,'String','Top Class',  'Style','text','Tag','txt.bringtotop',...
'Position',[0.025 0.620 0.250 0.045]);
f1h.btngrp.bringtotop = uibuttongroup('Parent',f1h.panel.unitcontrols,'Units','normalized',...
'BorderType','none','visible','on','Tag','btngrp.bringtotop',...
'SelectionChangeFcn',@highlightPointTrace,...
'Position',[0.295 0.620 0.680 0.045]);

for i = 1:5
   f1h.txtbox.unitnum(i)    = uicontrol('Parent',f1h.panel.unitcontrols,'Units','normalized',...
   'FontSize',9,'Enable','off',...
   'ListboxTop',0,'String','','Style','edit','Tag',['txtbox.unitnum(',num2str(i),')'],...
   'Position',[0.155+i*0.140 0.945 0.120 0.050],'BackgroundColor',col{i});

   f1h.txt.unitdprimeVal(i) = uicontrol('Parent',f1h.panel.unitcontrols,'Units','normalized',...
   'FontSize',9,'FontWeight','normal','HorizontalAlignment','center',...   
   'ListboxTop',0,'String','',        'Style','text',...
   'Tag',['txt.unitdprimeVal(',num2str(i),')'],...
   'Position',[0.155+i*0.140 0.880 0.120 0.050]);

   f1h.chkbx.unitsave(i)    = uicontrol('Parent',f1h.panel.unitcontrols,'Units','normalized',...
   'Style','checkbox','Tag',['chkbx.unitsave(',num2str(i),')'],'Value',0,'Enable','off',...
   'Position',[0.190+i*0.140 0.815 0.050 0.045],'BackgroundColor',get(f1h.fig.f1,'Color'));

   f1h.chkbx.showtraces(i)  = uicontrol('Parent',f1h.panel.unitcontrols,'Units','normalized',...
   'Style','checkbox','Tag',['chkbx.showtraces(',num2str(i),')'],'Value',0,'Enable','off',...
   'Position',[0.190+i*0.140 0.750 0.050 0.045],'BackgroundColor',get(f1h.fig.f1,'Color'),...
   'Callback',@showTraces);

   f1h.chkbx.meanwave(i)    = uicontrol('Parent',f1h.panel.unitcontrols,'Units','normalized',...
   'Style','checkbox','Tag',['chkbx.meanwave(',num2str(i),')'],'Value',0,'Enable','off',...
   'Position',[0.190+i*0.140 0.685 0.050 0.045],'BackgroundColor',get(f1h.fig.f1,'Color'),...
   'Callback',@showMeanTrace);

   f1h.radio.bringtotop(i)  = uicontrol('Parent',f1h.btngrp.bringtotop, 'Units','normalized',...
   'Style','radio',   'Tag',['radio.bringtotop(',num2str(i),')'],'Value',0,'Enable','off',...
   'Position',[(((115-50-6)/560)/2)+((137.5+2.5)/680)*(i-1) 0.000 50/680 1.000]);
end

% AZ20090220: Thresholding tool
f1h.txt.thresh = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'FontSize',10,'FontWeight','bold','HorizontalAlignment','left','Visible','on',...
'ListboxTop',0,'String','Threshold: +/-','Style','text','Tag','txt.thresh',...
'Position',[0.180 0.008 0.140 0.026]);
f1h.txtbox.thresh = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
'BackgroundColor',[1 1 1],'FontSize',9,'Visible','on',...
'Callback',@changeThreshold,...%'KeyPressFcn',@shortcutKeys,...
'ListboxTop',0,'String','32','Style','edit','Tag','txtbox.thresh',...
'Position',[0.320 0.008 0.040 0.028]);

f1h.chkbx.fixedsc = uicontrol('Parent',f1h.fig.f1,'Units','normalized','Enable','off',...
'String','Fixed Scaling','Style','radiobutton','Value',1,'Tag','chkbx.fixedsc',...
'Position',[0.038 0.011 0.132 0.019],'KeyPressFcn',@shortcutKeys);%,...
% f1h.chkbx.interact = uicontrol('Parent',f1h.fig.f1,'Units','normalized',...
% 'String','Interactive Plotting','Style','checkbox','Value',0,'Tag','chkbx.interact',...
% 'Position',[0.200 0.011 0.200 0.019],'Callback',@interactivePlotToggle,...
% 'KeyPressFcn',@shortcutKeys);

% f1h.plotInteractive = false;
f1h.highlights = [];


%% CREATE FUNCTIONS: username_CreateFcn (+ elecnum_CreateFcn + nclusters_CreateFcn)
% AZ 20081216: Sets username to username logged into computer
OSName = computer;
switch OSName
    case {'PCWIN','PCWIN64'}
        UserName = getenv('UserName');
        
        set(f1h.txtbox.elecnum,'BackgroundColor','white'); % from elecnum_CreateFcn
        
        if isequal(get(f1h.txtbox.username,'BackgroundColor'), ...
                     get(0,'defaultUicontrolBackgroundColor'))
                   set(f1h.txtbox.username,'BackgroundColor','white');
        end
        
        %% nclusters_CreateFcn
        if isequal(get(f1h.pop.nclusters,'BackgroundColor'), ...
                   get(0,'defaultUicontrolBackgroundColor'))
                   set(f1h.pop.nclusters,'BackgroundColor','white');
        end
    case {'GLNX86','GLNXA64','MACI','SOL64'}
        UserName = getenv('USER');
        
        set(f1h.txtbox.elecnum,'BackgroundColor', ...
         get(0,'defaultUicontrolBackgroundColor')); % from elecnum_CreateFcn
    otherwise
        %Leave usrtxt at default value of 'dario'
        UserName = 'dario';
end
set(f1h.txtbox.username,'String',UserName);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                            %% KEYPRESS FUNCTIONS %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
set(f1h.fig.f1,'KeyPressFcn',@shortcutKeys);


%% Original figure's closing function
%% HINT: If you can't close a window because of a CloseRequestFcn error, run:
%%       delete(get(0,'Children'))
function closefirstfigure(hObject, eventdata, handles)
    % If the new figure window the new button created is open ...
    if ~isempty(f1h.fig.f2)
        % Close it
        delete(f1h.fig.f2);
    end
    % Close the original figure
    delete(f1h.fig.f1);
end
% End of original figure's closing function

end